name: Release Dry Run

on:
  workflow_dispatch:

# default: least privileged permissions across all jobs
permissions:
  contents: read

jobs:
  release_dry_run:
    if: github.repository == 'LibreBooking/librebooking'
    runs-on: ubuntu-latest
    concurrency: release-dry-run
    environment: release

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7.0.0
        with:
          ref: develop
          fetch-depth: 0

      - name: Semantic Release (No-Op)
        uses: python-semantic-release/python-semantic-release@v10.6.1
        with:
          github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          config_file: releaserc.toml
          no_operation_mode: true
          build: false
